#!/usr/bin/env bash

#############################################################
#                   Quick Phylogeny                         #
#                    Sami El Hilali                         #
#                      2022/02/04                           #
#############################################################

# This script takes an orthoFinder output and create the alignments
# of single copy orthologues featured in the specified amount of species,
# then it trims the alignments and builds supergenes before running RAxML

################ PARSE PARAMETERS :

usage()
{
echo "--- QuickPhylogeny : from orthofinder to a tree using mafft,trimAl and RAxML --- usage :"
echo "-t number of threads"
echo "-s amount of species that have to feature an orthologue"
echo "-i input == OrthoFinder output path"
echo "-o outgroups for RAxML as a list separated by commas. enter none fo no outgroup"
echo "-r run name"
}

while getopts t:s:i:o:r:h option
do
	case "${option}" in
	t) THREADS=${OPTARG};;
	s) AMOUNT_OF_SPECIES=${OPTARG};;
	i) ORTHOFINDER_OUT_PATH=${OPTARG};;
	o) OUTGROUPS=${OPTARG};;
	r) RUN_NAME=${OPTARG};;
	h) usage
	   exit;;
	?) usage
           exit;;
	esac
done


#### OPTIONS :
OUTPUT_DIR=($(pwd))
INSTALL_PATH=<path to where is the folder here, so the script can call Get_SingleCopyOrthogroups_OF and CreateSuperGene>

# exit if a command fails :
set -e

echo "QuickPhylogeny was called with the following options :" > $OUTPUT_DIR/QuickPhylogeny_log.txt
echo "Quickphylogeny -t $THREADS -s $AMOUNT_OF_SPECIES -i $ORTHOFINDER_OUT_PATH -o $OUTGROUPS -r $RUN_NAME"
#### 1 - Align the single copy orthologues from OrthoFinder's output :
echo "##### Aligning Single copy orthologues" | tee -a $OUTPUT_DIR/QuickPhylogeny_log.txt
SPECIES=($(head -n 1 $ORTHOFINDER_OUT_PATH/Orthogroups/Orthogroups.tsv | cut -f2-))
echo "## species : ${SPECIES[*]}" | tee -a $OUTPUT_DIR/QuickPhylogeny_log.txt
# copy the Single copy orthologues file locally :
#if species == 0
if [[ $AMOUNT_OF_SPECIES -eq 0 ]]
then
	cat $ORTHOFINDER_OUT_PATH/Orthogroups/Orthogroups_SingleCopyOrthologues.txt <(echo "") > $OUTPUT_DIR/temp.selected_orthogroups.txt
else
	echo "$ORTHOFINDER_OUT_PATH"
	bash $INSTALL_PATH/Get_SingleCopyOrthogroups_OF -i "$ORTHOFINDER_OUT_PATH/Orthogroups/Orthogroups.GeneCount.tsv" -s "$AMOUNT_OF_SPECIES" -o "$OUTPUT_DIR/temp.selected_orthogroups.txt"
fi

AMOUNT_OF_SINGLE_COPY_ORTHOLOGUES=($(wc -l $OUTPUT_DIR/temp.selected_orthogroups.txt | cut -f1))
echo "## Single copy orthologues : $AMOUNT_OF_SINGLE_COPY_ORTHOLOGUES" | tee -a $OUTPUT_DIR/QuickPhylogeny_log.txt
#TODO# Add control that amount of Single copy orthologues is enough before proceeding

## First copy the sequences of Single copy orthologues :
mkdir -p $OUTPUT_DIR/mafft.$RUN_NAME

while read Orthogroup;
do
  cat $ORTHOFINDER_OUT_PATH/Orthogroup_Sequences/$Orthogroup.fa | sed -e 's/\*//g' > $OUTPUT_DIR/mafft.$RUN_NAME/$Orthogroup.unaligned.fa;
done < $OUTPUT_DIR/temp.selected_orthogroups.txt
##

## run mafft :
cd $OUTPUT_DIR/mafft.$RUN_NAME/

parallel -j $THREADS 'mafft --auto --anysymbol {} > {.}.aligned.fa' ::: *.unaligned.fa

echo "## DONE" | tee -a $OUTPUT_DIR/QuickPhylogeny_log.txt
##

## Concatenate aligned orthologues into supergenes :
cd $OUTPUT_DIR/

echo "##### Concatenate aligned orthologues into super genes" | tee -a $OUTPUT_DIR/QuickPhylogeny_log.txt

bash $INSTALL_PATH/CreateSuperGene -o "$OUTPUT_DIR" -a "$OUTPUT_DIR/mafft.$RUN_NAME" -i "$ORTHOFINDER_OUT_PATH" -s "$OUTPUT_DIR/temp.selected_orthogroups.txt"
echo "## DONE" | tee -a $OUTPUT_DIR/QuickPhylogeny_log.txt

## remove special AA U,J,X and trim the sequences in the file supergenes.fa created by CreateSuperGene (remove gappy positions) :
echo "##### Remove special AA and trim the gappy regions using trimAl" | tee -a $OUTPUT_DIR/QuickPhylogeny_log.txt

sed -e 's/U/-/g' -e 's/J/-/g' -e 's/X/-/g' -e 's/_/-/g' $OUTPUT_DIR/supergene.fa > $OUTPUT_DIR/supergene.rm_UJX.fa
trimal -in $OUTPUT_DIR/supergene.rm_UJX.fa -out $OUTPUT_DIR/supergene.rm_UJX.trim.$RUN_NAME.fa -noallgaps -automated1
echo "## DONE" | tee -a $OUTPUT_DIR/QuickPhylogeny_log.txt

## run RAxML with outgroups :
echo "##### run RAxML with outgroups :" | tee -a $OUTPUT_DIR/QuickPhylogeny_log.txt
if [[ $OUTGROUPS != "none" ]]
then
raxmlHPC-PTHREADS-SSE3 -m PROTGAMMAAUTO -o $OUTGROUPS -T $THREADS -n $RUN_NAME -p 12345 -s $OUTPUT_DIR/supergene.rm_UJX.trim.$RUN_NAME.fa
else
raxmlHPC-PTHREADS-SSE3 -m PROTGAMMAAUTO -T $THREADS -n $RUN_NAME -p 12345 -s $OUTPUT_DIR/supergene.rm_UJX.trim.$RUN_NAME.fa
fi

echo "## DONE"  | tee -a $OUTPUT_DIR/QuickPhylogeny_log.txt

rm $OUTPUT_DIR/temp.selected_orthogroups.txt
