#!/usr/bin/env bash

#############################################################
#                  Create Super Genes                       #
#                    Sami El Hilali                         #
#                      2021/07/08                           #
#############################################################

#OPTIONS :
while getopts o:a:i:s: option
do
	case "${option}"
	in
	o) OUTPUT_DIR=${OPTARG};;
	a) ALIGNED_PROTEOMES_PATH=${OPTARG};;
	i) ORTHOFINDER_OUT_PATH=${OPTARG};;
	s) SELECTED_ORTHOGROUPS=${OPTARG};;
	esac
done

#########################
# exit if a command fails
set -e
########

# create the file for genecounts and tsv of selected orthogroups :

head -n 1 $ORTHOFINDER_OUT_PATH/Orthogroups/Orthogroups.GeneCount.tsv > $OUTPUT_DIR/temp.selected_orthogroups.genecount.tsv

fgrep -f temp.selected_orthogroups.txt $ORTHOFINDER_OUT_PATH/Orthogroups/Orthogroups.GeneCount.tsv >> $OUTPUT_DIR/temp.selected_orthogroups.genecount.tsv
head -n 1 $ORTHOFINDER_OUT_PATH/Orthogroups/Orthogroups.tsv > $OUTPUT_DIR/temp.selected_orthogroups.tsv
fgrep -f temp.selected_orthogroups.txt $ORTHOFINDER_OUT_PATH/Orthogroups/Orthogroups.tsv >> $OUTPUT_DIR/temp.selected_orthogroups.tsv

ORTHOGROUPS_GENECOUNT=$OUTPUT_DIR/temp.selected_orthogroups.genecount.tsv
ORTHOGROUPS_TSV=$OUTPUT_DIR/temp.selected_orthogroups.tsv
#SELECTED_ORTHOGROUPS=$OUTPUT_DIR/temp.selected_orthogroups.txt

# get species IDs :
head -n 1 $ORTHOGROUPS_GENECOUNT | awk '{for(i=2;i<=(NF-1);i++) print $i"\t"i}' > $OUTPUT_DIR/temp.species
SUPERGENE_FASTA=$OUTPUT_DIR/supergene.fa

#########
#cut -f1 $ORTHOGROUPS_GENECOUNT | tail -n +2 > $OUTPUT_DIR/temp.selected_orthogroups.txt

# create the final fasta file :
> $SUPERGENE_FASTA

while read -r specie field
do

  echo ">$specie" >> $SUPERGENE_FASTA
  #> $OUTPUT_DIR/$specie.fa
  while read -r Orthogroup
  do
  specie_is_in_orthogroup=($(fgrep $Orthogroup $ORTHOGROUPS_GENECOUNT | awk -F "\t" -v field=$field '{print $field}'))
  #echo "$specie $Orthogroup $specie_is_in_orthogroup"
  # if specie have sequence in orthogroup :
  if [[ $specie_is_in_orthogroup -eq 1 ]]
  then
    protein_id_in_specie=($(fgrep $Orthogroup $ORTHOGROUPS_TSV | awk -F "\t" -v field=$field '{print $field}'))
    #fgrep $Orthogroup $ORTHOGROUPS_TSV | awk -F "\t" -v field=$field '{print $field}' > temp.protein_id
    echo $protein_id_in_specie > $OUTPUT_DIR/temp.protein_id
    seqtk subseq $ALIGNED_PROTEOMES_PATH/$Orthogroup.unaligned.aligned.fa $OUTPUT_DIR/temp.protein_id | grep -v ">" | sed -e 's/\*/-/g' | tr -d '\n' >> $SUPERGENE_FASTA
    #seqtk subseq $ALIGNED_PROTEOMES_PATH/$Orthogroup.unaligned.aligned.fa $OUTPUT_DIR/temp.protein_id | sed -e 's/\*//g' >> $OUTPUT_DIR/$specie.fa
  # if specie have not sequence in orthogroup :
  else
    protein_id_in_orthogroup=($(fgrep ">" $ALIGNED_PROTEOMES_PATH/$Orthogroup.unaligned.aligned.fa | head -n 1 | sed -e 's/>//g'))
    echo $protein_id_in_orthogroup > $OUTPUT_DIR/temp.protein_id
    seqtk subseq $ALIGNED_PROTEOMES_PATH/$Orthogroup.unaligned.aligned.fa $OUTPUT_DIR/temp.protein_id | grep -v ">" | sed -e 's/\*/-/g' -e 's/[A-Z]/-/g' | tr -d '\n' >> $SUPERGENE_FASTA
  fi
  done < $SELECTED_ORTHOGROUPS
  echo "" >> $SUPERGENE_FASTA
done < $OUTPUT_DIR/temp.species

wait

rm $OUTPUT_DIR/temp.species $OUTPUT_DIR/temp.protein_id $ORTHOGROUPS_GENECOUNT $ORTHOGROUPS_TSV
